### PR TITLE
Introduce Lombok to reduce boilerplate

### PR DESCRIPTION
**Pull request by quidryan**
Leverage Lombok to reduce boilerplate code, to enhance readability and avoid bugs from manual entry. E.g. there were a few == on Strings in equals methods, which are invalid. Lombok helps highlight what is relevant in a class, by removing boilerplate code but also being more declarative about the intentions of the fields, e.g. a @Getter on a class member makes it real clear that that field will have a public getter method and having an explicit list of fields that constitute the equals/hashCode makes it more clear the members involved. Hand-crafted equals/hashCode is a source of possible errors, that just doesn't have to exist anymore in Java. Most importantly, the resulting code is easier to read and cleaner.

* This has no breaking protocol changes. 
* The java code has one interface change and that was to standardize on getCompressionAlgorithm, there were both getCompressionAlgorithm and getCompressionAlgo in the code.
* Aligned class member names to the name of the getter method, to reduce cognitive load
* Moved variables, in code related to the other changes, to the top of the class to follow common coding conventions.
* Removed misnomer static from enums, and unneeded "public" clarification on interfaces.

### CODE REVIEW

**Comment by quidryan** [comment]
CC @wmiaw @dreynaud, I'd include Venky but I don't know his Github handle.

**Comment by wmiaw** [comment]
@quidryan I intend to reject this pull request for the following reasons:

* It adds a project dependency that is not technically required to make things work. This isn't horrible to some people, but it is something I have explicitly decided to keep out of MSL core if at all possible. Same reason MSL core does not include Guice annotations.
* I don't see how his will work properly with all development environments (Eclipse, IntelliJ, Emacs, vi, jEdit, etc.) and related tools (e.g. JTags) or with Javadoc.
* The changes make the code completely broken if you don't want to or cannot use Lombok for whatever reason (perhaps it is not an approved library or tool for your security project). The only other annotations in the code base are for JUnit or TestNG but the tests can still be run properly if those annotations are ignored, with different test runners or test frameworks—the code is still valid and complete. And those are for the unit tests.
* I'm split between the loss of information that must then be gleaned out of understanding Lombok. If coming from another language, I can understand how I am supposed to implement equals or hashCode() for the matching code in the other language when it is written out. Probably not so when annotations are being used to hide things and a tool must be used (lombok.jar) to generate valid Java code. But I do like auto-generated code that will be less error-prone. If this was part of the core JDK I'd be very happy to include it.

Separate from Lombok, the variables at the end of classes, explicit inclusion of modifiers that are optional, certain use of white space and newlines, and current variable names are the coding convention used in this code base. Although I admit it is not 100% consistent right now (particularly in the JavaScript, due to lack of real variable scope restrictions).

Also, corresponding changes such as variable names haven't been made to the JavaScript code base. That would be necessary before merging in this pull request.

If you found broken == then we should double-check the JavaScript code.

**Comment by quidryan** [comment]
This PR introduces no dependencies. Lombok is a "provided" dependency, it is NOT a runtime dependency. You can look at the resulting pom file check.

Lombok is using annotation processing, anyone using the java compiler will be compatible since it's a standard feature. Modern tools all support annotation processor, including Gradle, Maven, IntelliJ, NetBeans, and Eclipse. Please follow the documentation on the projectlombok.org site if you need help. If you're in a text editor, there isn't any tab-completion like feature, so what can't work? I'm happy to help anyone who tries to contribute to the project that needs help with Lombok.

If the project is going to be limited to by what "someone" "might" not be allowed to use, is a critical blow the innovation to the project. Having enough users that this is a real problem would be great, but the project isn't there. We need to push past this ambiguous limitation.

You're conflating support for javascript with the maintainability of Java, I don't see the need for this. For an open source project to be successful, it needs to be as clean, efficient and understandable as possible. If keeping two languages in strict sync forces us to sacrifice on any of those elements, the project will not be as great as it could be.

This PR makes changes internal to the Java implementation, I don't see why it would require javascript changes. The protocol hasn't changed.

I appreciate the long response, but this PR is important to future innovation. It addresses your specific statement of keeping the code base "clean". I setup a meeting to discuss further.

**Comment by wmiaw** [comment]
Without Lombok, the Java code will not compile. That's a dependency to me.

Yes, anyone using Java can use Lombok. But anyone doing Java development cannot use the Java code that has been annotated using Lombok. For example, doing a find for a call to getX() will no longer find anything since that function doesn't exist. And tools like JTags or LXR won't be able to find cross references on the raw code. Emacs, vi, jEdit, etc. are all text editors that have plug-ins or integrations for Java which can have auto-complete, cross-referencing capabilities, etc. I did read up on the Lombok project and it looks like I am not the only one who thinks Lombok has serious problems.

Right now, except for BouncyCastle and org.json, there are no required Java dependencies. Even the Gradle integration is completely optional and someone who doesn't use Gradle or hates Gradle can take advantage of the existing code base as-is. Lombok would make that no longer true.

I do not think limiting the project to what I believe is a reasonable common denominator of compatibility is a critical blow to the innovation capabilities of this project. Not using Lombok does not prevent us from adding features or changes.

My comments about JavaScript have to do with maintainability of the project. One of the primary reasons I have kept certain code structures, comment blocks, variable names, even file names the way they are is so they are identical across languages. This makes it easy to find the same code in the different language code bases to keep their feature set, code, and compatibility in sync and maintained together at the same time. It is not only about the protocol.

We can discuss further why you believe this is necessary for future innovation at the meeting you plan to set up.

**Pull request closed without merging**
