### PR TITLE
MslControl: avoid code duplication with multi-catch blocks

### PR DESCRIPTION
**Pull request by dreynaud**
(should) behave the same in less lines.

### CODE REVIEW

**Comment by dreynaud** [comment]
CC @quidryan @wmiaw

**Comment by dreynaud** [comment]
I couldn't find the Java version we're supposed to target (in terms of source compatibility). Multi-catch is a Java 7 thing, released July 2011.

**Comment by wmiaw** [comment]
Yeah, I had started using multicatch at one point but it wasn't compatible at the time, since MSL code was started when Netflix was still on Java 6. I'm not opposed to using multicatch, but I'm not as keen on the small breakout function as I don't think that one buys much versus hiding some details. Anyway, I'll take a look at this in detail later. Thanks.

**Comment by wmiaw** [comment]
This change got rolled into pull request #107.

**Pull request closed without merging**
