### PR TITLE
Remove project files

### PR DESCRIPTION
**Pull request by dreynaud**

### CODE REVIEW

**Comment by dreynaud** [comment]
image

Also note that when starting with fresh project files, IntelliJ 15 automatically detects the various web.xml's and sets up facets based on these.

**Comment by dreynaud** [comment]
CC @quidryan

**Comment by wmiaw** [comment]
The newest version of IntelliJ still doesn't automatically configure the project web contexts properly, but it also doesn't seem to support any way to do this in a user-independent way from existing .idea files anymore either.

I have made changes to the top-level README to provide instructions for manual configuration.

**Comment by wmiaw** [comment]
I have removed the .idea files and added /.idea to the top-level .gitignore file. Did not want to pull in the other changes to .gitignore in this pull request.

**Pull request closed without merging**
