### PR TITLE
Restructure project layout

### PR DESCRIPTION
**Pull request by quidryan**
This PR applies some canonical Gradle patterns to the project. It should make it easier to reason about the project, and expand it in the future to handle more examples and tangential features like the CLI.

Expect to see the logical projects separated into Gradle modules, so that they can have their own lifecycle and dependencies.  Since the IDEs can load them natively, there's no need for IDE files to be checked in. There are also no .jar files checked in anymore, they've been replaced with actual dependencies, and each module can be published independently.

One nice perk is that the integration tests use gretty to start a jetty/tomcat before the tests automatically. I.e. Just running test will fully run both the unit tests and all the integ-tests.

### CODE REVIEW

**Comment by wmiaw** [comment]
Vadim and I have been discussing this a bit. But the proposed layout doesn't match as well what I would like. Some thoughts:
* I would still want the mock implementations to be inside the unit test directory.
* I would still like to have an examples directory, with subdirectories under it for the individual examples. Not sure if this is possible with Gradle, particularly given the dependency chain, but I hope it is.
* IDE files are necessary for people who aren't going to use Gradle and want integration into the IDE web server deployment.
* JAR files were checked in to facilitate people who are not using Gradle.

**Comment by quidryan** [comment]
I can understand wanting Mocks in the test directory, except that you're using them in Burp and integ-tests, and IntelliJ can't have one module depend on another modules test artifacts. That said, if you're using the Mock classes in anything but a test, that tells me that they're actually needed as "main" code. I would content that the way you're using them, they are not pure test Mocks and are perfectly fine in the "main" code.

I've worked on pretty much every other Netflix OSS project and everyone requires users to use the provided build system, and we've never heard a complaint, other than "I wish it was Maven". We also have the added benefit of checking in the gradle wrapper, so users don't even need to download Gradle, it's there for them.  I strongly believe relying on a standard build system will deter people from using the project. I could argue that by not using a standard layout with normal dependencies that we are creating a barrier to entry.

Checking in .jars is a build anti-pattern, which also makes it impossible to publish since consumers would not see dependencies in the module descriptor (aka the POM). If you want MSL to be published to Maven Central, then the jars will have to stay as dependencies. 

I will update to put examples into a sub-directory.

**Comment by semmypurewal** [comment]
I agree with @quidryan here, and I've been suggesting similar changes for the JavaScript code (specifically, using the CommonJS module format and a build-system). I think we're creating a barrier to entry by not following standard practices.

**Comment by wmiaw** [comment]
I think @sukhmal should address the issue of Burp and the integration tests having dependencies on unit test classes. But that can be addressed better. The mock implementations shouldn't be in the core code tree.

I'm not saying we should not make everything with with Gradle. I was only saying the Eclipse and IntelliJ support should also be there. Are you saying that they are somehow incompatible? (To which I say why would anyone make a build system that is incompatible with existing code organization—e.g. Gradle directory requirements). I think supporting more options is the opposite of a barrier.

I'm okay with removing the JARs inside.

**Comment by quidryan** [comment]
IntelliJ and Eclipse both have native support for Gradle projects, so no IDE files need to be checked in. Which also means that changes in the build files will be reflected in the IDE.

Regarding the dircectory structure, Gradle can handle dependency on test classes no problem, it's IntelliJ (and maybe eclipse) that has the problem. I had a branch were I published the Mocks in their own module so that they could be shared, but then I had a cycle where MSL's tests depends on the mocks and the mocks depend on MSL core code. Once again, Gradle was fine with this, but IntelliJ will not allow a cycle. I'll take a stab at putting the tests in their own module, so that they can be published, which will keep the IDEs happy.

**Comment by wmiaw** [comment]
Eclipse and IntelliJ cannot pull in the WEB-INF stuff for web server deployment, from a Gradle configuration file, AFAIK. Am I incorrect?

The unit tests being in their own module is what I was thinking. Thanks. If IntelliJ is still unhappy... :-(

**Comment by quidryan** [comment]
Can you elaborate on the web server deployment part? I honestly just haven't used IntelliJ's servlet container support. I know a few teams at Netflix have configured that aspect of the IDE from Gradle, but I haven't. I'll give it a try, but it would be useful to know what the experience is like in the IDE, so I can ensure it works.

**Comment by wmiaw** [comment]
Eclipse and IntelliJ both have ways you can configure your project for automatic deployment to a web server like Tomcat, with support for debugging and dynamic code changes. I didn't see anything like IDE-integration supported in stock Gradle when I looked? I think if you look in the IDE config files the parts that reference WEB-INF and Tomcat are probably the parts that matter.

**Comment by quidryan** [comment]
I've updated to fix the javascript tests and leave the Mocks out of the production code.

I have not worked on the the IDE support. I still don't know exactly that means in the IDE, which makes it hard to replicate. I know of a few dozen examples where projects have had added tighter IDE integration to a Gradle file, but it's always a little customized to their environment. So maybe I'm missing something, since it doesn't make sense to me to check-in customization that are specific to a user. I know that no other Netflix oss project has done this and they've been fine. I've attached a screen of what it looks like by importing the project directly using the native Gradle support, and I'm seeing it pick up on the fact that a project is a web project. I'm not sure what else would be needed.

screen shot 2015-08-11 at 4 56 31 pm

I propose that we table specific further IDE web support for now, and when I learn more about what you're referring to, we can add it later. Anything else this PR needs?

**Comment by wmiaw** [comment]
That sounds reasonable. I will check the IDE integration after this change gets merged and see what issues there might be. @sukhmal or I can fix the mock implementation dependencies mentioned earlier. Will review now.

**Pull request merged**
