### PR TITLE
Increase readability of equals/hashCode for MessageHeader/ErrorHeader

### PR DESCRIPTION
**Pull request by quidryan**
Also avoid == on strings, even if it's to check if both are null.

### CODE REVIEW

**Comment by wmiaw** [comment]
The use of Objects functions is OK, but please do not change coding style or variable names. Also, use instanceof instead of comparing the Class types using == because that will prevent subclasses from properly using the parent class equals() function.

**Comment by quidryan** [comment]
I fixed the getClass() to use instanceof, that was a problem.

I don't understand what you're saying about changing coding style or variable names. I didn't change any variable names, I only introduced one variable called target and the arguments to equals is still called obj. Can you be more specific?

What coding style faux-pas did I commit? Please point me to your style guide and I was follow it. We typically use the [Google's style guide](https://google.github.io/styleguide/javaguide.html).

**Comment by wmiaw** [comment]
I wouldn't call it a faux-pas :) But for example: `if (obj == this) return true;` on one line, without braces and a new line. There is no published style guide, and style just has to be picked up by observation.

The changed variable name is `other` instead of `that`. `that` is used consistently in all of the classes and also in the JavaScript. Thanks.

**Comment by quidryan** [comment]
Gotch ya. I had to stare at it for a while to find the one line without braces, uses braces is so common in internal code that I just couldn't see it.

**Comment by quidryan** [comment]
@wmiaw Regarding braces: https://blog.codecentric.de/en/2014/02/curly-braces/

**Comment by wmiaw** [comment]
Turns out Objects.equals() is not exactly the same as the logic originally written. And I think it will try to box primitives, which won't work right if those primitives are null, probably. I'm going to revert the equals() changes.

**Comment by quidryan** [comment]
Why not write a test to prove one way or another? How could primitives be
null? There's no case where a primitive gets boxed and it turns out to be
null.

**Comment by wmiaw** [comment]
You're right, I messed up on that statement. I must have been thinking of something else while I was writing it.

I just wanted to get things back to where I know it will do the right thing for now, for example also when Objects.equals() does (a == b) but I want to explicitly only allow that if they are both null. It can get changed to something nicer when there's more time.

**Pull request merged**
